name: template_env
### Note that you could remove all the version tags in this document
### to get conda/mamba to install the (inter-compatible) latest version 
### of all dependencies;
### When you finish the project, you can copy the version numbers from 
### `conda list -n env_name` to this document, so you freeze them for the next user.

channels:
- defaults
dependencies:
- python # Needed to run python
- pip # Needed to enable pip install inside conda envs,


# Below are examples of project-specific python and R packages (including versions)

# python packages
- pytorch=*=*cuda*
- numpy
- pandas
- pytest

